### ISSUE TITLE
Fork consolidation

### ISSUE THREAD

**Issue by huerlisi** [betterplace/mt940_parser#11]
First off: Big "thank you" for working on this nice package. We're using it in Bookyt with great success:-)

There's a couple of forks out there, each providing some missing support or fixing some issues. My branch at https://github.com/CyTeam/mt940_parser is among those. I just got a [PR by @alexanderadam](https://github.com/CyTeam/mt940_parser/pull/2) fixing an issue with some banks.

Now, I'd like to have this fix upstream, in a released version.

Unfortunately when I needed the library it failed to parse the files I had and I found out that it was a bit too opinionated about some fields. @tom025 had a [nice branch ](https://github.com/LyagushkaLimited/mt940_parser)with some changes that worked for me. But they are a bit intrusive, so simply merging is not possible.

I went through the changes again to see if we could get the branches merged again. Here's a list of the relevant changes:
- introduce rspec unit tests
- Add OpeningBalance
- Change meaning of
  *\* 25/Account
  *\* 28/Statement
  *\* 68/StatementLineInformation
  The other changes are mostly non-functional and could be ignored IMHO.

I think adding the OpeningBalance is a no-brainer, just needs to be ported.

The additional specs seem to be nice, but could well be ported to test-unit. They also mostly tackle the changed classes for 25,28,68. Which brings us to the most tricky part:

The classes for Account, Statement, StatementLineInformation are more opiniated regarding content of the fields than the MT940 spec describes. They parse implementation specific fields. @tom025 therefore deprecates and replaces them with implementations that are closer to the standard. He delegates unknown methods back to the old implementations, but with a deprecation warning.

As mentioned your gem failed on my files because it expected non-standard field formats. Therefore I really would like to see the changes in this area integrated.

Question: would you accept PRs that supersede the mentioned classes with new implementations as visible in our branch at https://github.com/CyTeam/mt940_parser?

**Comment by tordans** [comment]
Hi @huerlisi thank for taking the time to create this issue. I just wanted to let you know that we saw it and will look into it soon, probably next week.
Until then, Tobias

**Comment by averell23** [comment]
Hi @huerlisi - great to know people are finding our code useful, and that you took the time to improve on things.

We wrote this gem mainly for our internal use; it works solidly for us ever since but we never tested with non-internal cases, as our time to do so is limited.

In any case, the changes to the parser seem reasonable, even if the bottom line is that some parsing has to be done by the end user of the data.

In order to evaluate the changes, it would be great if you could make a pull request that only includes the important stuff. 

It'd help us if you stick test-unit for the PR; mostly so that we can see that everything still passes the original tests. When we have that PR, we can also validate things against our internal system check if it can be merged as is or needs further discussion.

If you've got more on your plate, I'd prefer to deal with that in separate PRs to keep things manageable.

Thanks,
                    Daniel

**Comment by huerlisi** [comment]
Hi @averell23 

Cool, will go ahead with this soon.

**Comment by fwolfst** [comment]
Can be closed I guess. Looks somewhat stale.

**Comment by fwolfst** [comment]
@huerlisi And thanks!
